import { test, expect } from '@playwright/test'
import { setup, current } from './fixture'
async function chooseSix(page: import('@playwright/test').Page) {
  for (let i = 0; i < 4; i++)
    await page.getByRole('button', { name: '主选', exact: true }).nth(i).click()
  for (let i = 4; i < 6; i++)
    await page.getByRole('button', { name: '备选', exact: true }).nth(i).click()
}
test('未登录不能读取目录，登录携带 CSRF 并进入学生选课', async ({ page }) => {
  const state = await setup(page)
  state.user = null
  await page.goto('/catalog')
  await expect(page).toHaveURL(/login/)
  await page.getByPlaceholder('请输入账号').fill('tester')
  await page.getByPlaceholder('请输入密码').fill('private-test-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/catalog/)
  expect(state.headers.find((h) => h.path === '/auth/login').headers['x-csrf-token']).toBeTruthy()
  expect(await page.evaluate(() => localStorage.length)).toBe(0)
})
test('登录失败留在页面并清空密码', async ({ page }) => {
  const state = await setup(page)
  state.user = null
  state.loginError = true
  await page.goto('/login')
  await page.getByPlaceholder('请输入账号').fill('tester')
  await page.getByPlaceholder('请输入密码').fill('wrong')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByText('账号或密码错误')).toBeVisible()
  await expect(page.getByPlaceholder('请输入密码')).toHaveValue('')
})
for (const [role, path] of [
  ['STUDENT', 'student/registration'],
  ['PROFESSOR', 'professor/teaching'],
  ['REGISTRAR', 'registrar/registration'],
])
  test(`${role}默认入口`, async ({ page }) => {
    await setup(page, role)
    await page.goto('/')
    await expect(page).toHaveURL(new RegExp(path))
  })
test('学生跨角色导航被拒绝', async ({ page }) => {
  await setup(page)
  await page.goto('/registrar/students')
  await expect(page.getByText('当前账号无权访问此页面')).toBeVisible()
})
test('草稿不改变有效课表，初次提交强制四主选两备选', async ({ page }) => {
  const state = await setup(page)
  await page.goto('/student/registration')
  await page.getByRole('button', { name: '主选', exact: true }).first().click()
  await page.getByRole('button', { name: '预检并提交' }).click()
  await expect(page.getByText(/首次正式提交必须选择四门/)).toBeVisible()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => state.savedDraft).not.toBeNull()
  expect(state.savedDraft.primaryOfferingIds).toEqual(['100'])
  expect(state.submissions).toBe(0)
  expect(state.schedule.enrollments).toEqual([])
  expect(state.headers.find((h) => h.path.endsWith('/draft')).headers['if-match']).toBe('"0"')
})
test('四主选两备选经过预检确认，提交只注册四门', async ({ page }) => {
  const state = await setup(page)
  await page.goto('/student/registration')
  await chooseSix(page)
  await page.getByRole('button', { name: '预检并提交' }).click()
  await expect(page.getByText('确认提交选课方案')).toBeVisible()
  expect(state.submissions).toBe(0)
  await page.getByRole('button', { name: '正式提交', exact: true }).click()
  await expect.poll(() => state.submissions).toBe(1)
  expect(state.schedule.enrollments).toHaveLength(4)
  await page.getByRole('tab', { name: '当前有效课表' }).click()
  await expect(page.getByText('已注册', { exact: true })).toBeVisible()
})
test('先修失败展示具体课程并阻止正式提交', async ({ page }) => {
  const state = await setup(page)
  state.validationError = true
  await page.goto('/student/registration')
  await chooseSix(page)
  await page.getByRole('button', { name: '预检并提交' }).click()
  await expect(page.getByText('数据库原理：先修课未通过')).toBeVisible()
  expect(state.submissions).toBe(0)
})
test('版本冲突后禁止重复提交，保留本地方案供刷新核对', async ({ page }) => {
  const state = await setup(page)
  state.staleSubmit = true
  await page.goto('/student/registration')
  await chooseSix(page)
  await page.getByRole('button', { name: '预检并提交' }).click()
  await page.getByRole('button', { name: '正式提交', exact: true }).click()
  await expect(page.getByText('课表版本已变化')).toBeVisible()
  await expect(page.getByRole('button', { name: '预检并提交' })).toBeDisabled()
  expect(state.submissions).toBe(1)
})
test('删除课表取消无变化，确认才请求接口', async ({ page }) => {
  const state = await setup(page)
  await page.goto('/student/registration')
  await page.getByRole('button', { name: '删除整个课表', exact: true }).click()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  expect(state.deletes).toBe(0)
  await page.getByRole('button', { name: '删除整个课表', exact: true }).click()
  await page.getByRole('button', { name: '确认删除' }).click()
  await expect.poll(() => state.deletes).toBe(1)
})
test('关闭的学期不能修改工作方案', async ({ page }) => {
  const state = await setup(page)
  state.semesters[0].status = 'CLOSED'
  await page.goto('/student/registration')
  await expect(page.getByRole('button', { name: '保存草稿', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '主选', exact: true }).first()).toBeDisabled()
})
test('目录故障明确提示而不伪装为空目录', async ({ page }) => {
  const state = await setup(page)
  state.catalogError = true
  await page.goto('/catalog')
  await expect(page.getByText('目录暂不可用，请稍后重试')).toBeVisible()
  await expect(page.getByRole('button', { name: '重新加载' })).toBeVisible()
})
test('成绩单区分未录入和 I，不存储本地成绩', async ({ page }) => {
  await setup(page)
  await page.goto('/student/report-card')
  await expect(page.getByText('未录入', { exact: true })).toBeVisible()
  await expect(page.getByText('I', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => [localStorage.length, sessionStorage.length])).toEqual([0, 0])
})
test('教师成绩只发送修改行，区分无记录和已有版本0', async ({ page }) => {
  const state = await setup(page, 'PROFESSOR')
  await page.goto('/professor/offerings/100/roster')
  await page.getByRole('combobox', { name: '张同学的成绩' }).press('Enter')
  await page
    .getByRole('listbox', { name: '张同学的成绩' })
    .getByRole('option', { name: 'B', exact: true })
    .click()
  await page.getByRole('combobox', { name: '李同学的成绩' }).press('Enter')
  await page
    .getByRole('listbox', { name: '李同学的成绩' })
    .getByRole('option', { name: 'C', exact: true })
    .click()
  await page.getByRole('button', { name: '保存 2 项修改' }).click()
  await page.getByRole('button', { name: '确认保存', exact: true }).click()
  await expect.poll(() => state.grades).not.toBeNull()
  expect(state.grades.entries).toEqual([
    { enrollmentId: '900', grade: 'B', expectedVersion: null },
    { enrollmentId: '901', grade: 'C', expectedVersion: 0 },
  ])
})
test('教务编辑不发送掩码或空密码，不越权修改账号', async ({ page }) => {
  const state = await setup(page, 'REGISTRAR')
  await page.goto('/registrar/students')
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByRole('dialog').getByLabel('姓名', { exact: true }).fill('更新姓名')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect.poll(() => state.newPerson).not.toBeNull()
  expect(state.newPerson.name).toBe('更新姓名')
  expect(state.newPerson).not.toHaveProperty('socialSecurityNumber')
  expect(state.newPerson).not.toHaveProperty('username')
  expect(state.newPerson).not.toHaveProperty('password')
})
test('有关联的师生删除显示拒绝原因', async ({ page }) => {
  const state = await setup(page, 'REGISTRAR')
  state.personnelConflict = true
  await page.goto('/registrar/students')
  await page.getByRole('button', { name: '删除', exact: true }).first().click()
  await page.getByRole('dialog').getByRole('button', { name: '删除', exact: true }).click()
  await expect(page.getByText('存在当前注册关联，无法删除')).toBeVisible()
})
test('教务到截止时间才可关闭，关闭显示取消与待重试通知', async ({ page }) => {
  const state = await setup(page, 'REGISTRAR')
  state.semesters[0].addDropEnd = new Date(Date.now() - 10000).toISOString()
  await page.goto('/registrar/registration')
  await page.getByRole('button', { name: '关闭注册', exact: true }).click()
  await page.getByRole('button', { name: '确认关闭', exact: true }).click()
  await expect(page.getByText('不足三人', { exact: true })).toBeVisible()
  await expect(page.getByText('财务服务暂不可达', { exact: true })).toBeVisible()
  expect(state.closeCount).toBe(1)
})
test('在途事务关闭失败明确提示且不显示成功结果', async ({ page }) => {
  const state = await setup(page, 'REGISTRAR')
  state.semesters[0].addDropEnd = new Date(Date.now() - 10000).toISOString()
  state.closeBusy = true
  await page.goto('/registrar/registration')
  await page.getByRole('button', { name: '关闭注册', exact: true }).click()
  await page.getByRole('button', { name: '确认关闭', exact: true }).click()
  await expect(page.getByText('有注册变更正在处理，请稍后重试')).toBeVisible()
  expect(state.closeResult).toBeNull()
})
test('过期后同一账号可恢复内存草稿', async ({ page }) => {
  const state = await setup(page)
  await page.goto('/student/registration')
  await page.getByRole('button', { name: '主选', exact: true }).first().click()
  state.availability401 = true
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page).toHaveURL(/login/)
  await page.getByPlaceholder('请输入账号').fill('tester')
  await page.getByPlaceholder('请输入密码').fill('test-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByText('恢复工作方案', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '恢复方案', exact: true }).click()
  await expect(page.locator('.choice-slot.filled')).toHaveCount(1)
})
test('手机导航可用且页面不横向溢出', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setup(page)
  await page.goto('/student/registration')
  await expect(page.getByRole('heading', { name: '选课中心' })).toBeVisible()
  expect(
    await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1),
  ).toBeTruthy()
  await page.getByRole('tab', { name: '课程目录', exact: true }).click()
  await page.screenshot({ path: 'test-results/mobile-registration.png', fullPage: true })
  await page.getByRole('button', { name: '打开导航' }).click()
  await page.locator('.mobile-nav').getByRole('link', { name: '成绩单' }).click()
  await expect(page).toHaveURL(/report-card/)
  expect(
    await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1),
  ).toBeTruthy()
})
test('教师选择提交完整授课集合并带版本', async ({ page }) => {
  const state = await setup(page, 'PROFESSOR')
  await page.goto('/professor/teaching')
  await page.getByRole('checkbox', { name: '选择数据库原理01班' }).check()
  await page.getByRole('button', { name: '保存授课方案', exact: true }).click()
  await page.getByRole('button', { name: '保存方案', exact: true }).click()
  await expect.poll(() => state.teaching.selectedOfferingIds).toEqual(['100', '101'])
  expect(state.headers.find((h) => h.path.includes('/teaching/')).headers['if-match']).toBe('"0"')
})
test('满员变化在编辑过程中提示，备选可调整顺序', async ({ page }) => {
  const state = await setup(page)
  await page.goto('/student/registration')
  await chooseSix(page)
  state.offerings[0].enrolledCount = 10
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.getByText(/软件工程 名额已满/)).toBeVisible()
  await page.getByRole('button', { name: '上移优先级' }).click()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => state.savedDraft?.alternateOfferingIds).toEqual(['105', '104'])
})
test('成绩修改未保存时离开可取消', async ({ page }) => {
  await setup(page, 'PROFESSOR')
  await page.goto('/professor/offerings/100/roster')
  await page.getByRole('combobox', { name: '张同学的成绩' }).press('Enter')
  await page
    .getByRole('listbox', { name: '张同学的成绩' })
    .getByRole('option', { name: 'A', exact: true })
    .click()
  await page.getByRole('link', { name: '← 返回教学班' }).click()
  await page.getByRole('button', { name: '继续编辑', exact: true }).click()
  await expect(page).toHaveURL(/roster/)
  await expect(page.getByRole('button', { name: '保存 1 项修改' })).toBeEnabled()
})
test('新增师生允许空 SSN，教师院系和日期需完整', async ({ page }) => {
  const state = await setup(page, 'REGISTRAR')
  await page.goto('/registrar/professors')
  await page.getByRole('button', { name: '新增教师', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('登录账号', { exact: true }).fill('newprof')
  await dialog.getByLabel('姓名', { exact: true }).fill('新教师')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText('请选择出生日期', { exact: true })).toBeVisible()
  expect(state.newPerson).toBeNull()
  await dialog.getByPlaceholder('选择日期').click()
  await page
    .locator('.el-picker-panel')
    .getByText(String(new Date().getDate()), { exact: true })
    .last()
    .click()
  await dialog.getByLabel('院系', { exact: true }).fill('计算机学院')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect.poll(() => state.newPerson).not.toBeNull()
  expect(state.newPerson).not.toHaveProperty('socialSecurityNumber')
  expect(state.newPerson).not.toHaveProperty('password')
})
test('主动退出清除工作方案，重新登录不恢复', async ({ page }) => {
  const state = await setup(page)
  await page.goto('/student/registration')
  await page.getByRole('button', { name: '主选', exact: true }).first().click()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await page.getByRole('button', { name: '退出', exact: true }).click()
  await expect(page).toHaveURL(/login/)
  expect(state.user).toBeNull()
  await page.getByPlaceholder('请输入账号').fill('tester')
  await page.getByPlaceholder('请输入密码').fill('test')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '选课中心' })).toBeVisible()
  await expect(page.getByText('恢复工作方案', { exact: true })).toHaveCount(0)
  await expect(page.locator('.choice-slot.filled')).toHaveCount(0)
})
test('真实连接错误显示重试而非模拟数据', async ({ page }) => {
  await page.route('**/api/v1/**', (route) => route.abort('connectionrefused'))
  await page.goto('/login')
  await page.getByPlaceholder('请输入账号').fill('tester')
  await page.getByPlaceholder('请输入密码').fill('test')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByText(/无法连接服务/)).toBeVisible()
  await expect(page).toHaveURL(/login/)
  await page.screenshot({ path: 'test-results/login-connection-error.png', fullPage: true })
})
test('桌面选课视觉检查与控制台无异常', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await setup(page)
  await page.goto('/student/registration')
  await chooseSix(page)
  await page.screenshot({ path: 'test-results/desktop-registration.png', fullPage: true })
  expect(errors).toEqual([])
})
